import { v4 as uuidv4 } from 'uuid'
import { saveSnapshot, getSnapshots } from './db.js'

// Simple compression using btoa — no external dependency needed
function compress(str) {
  return btoa(encodeURIComponent(str))
}

function decompress(str) {
  return decodeURIComponent(atob(str))
}

// Auto-label generators per module
function autoLabel(moduleId, state) {
  try {
    switch (moduleId) {
      case 'playground': {
        const params = state.parameters ?? {}
        const parts = Object.entries(params)
          .slice(0, 3)
          .map(([k, v]) => `${k}=${typeof v === 'number' ? (v >= 1000 ? `${(v/1000).toFixed(0)}k` : v) : v}`)
        return parts.length ? parts.join(', ') : 'Parameter snapshot'
      }
      case 'notebook': {
        const entries = state.entries ?? []
        const last = entries[entries.length - 1]
        return last?.title ? `Added: ${last.title}` : 'Notebook snapshot'
      }
      case 'bom': {
        const items = state.items ?? []
        const cost = items.reduce((s, i) => s + (i.quantity ?? 1) * (i.unitPrice ?? 0), 0)
        return `${items.length} items, $${cost.toFixed(2)} total`
      }
      case 'debug': {
        const lines = (state.code ?? '').split('\n').length
        return `${lines} lines`
      }
      case 'brain': {
        return `Project Brain snapshot`
      }
      case 'cad': {
        return `After AI analysis`
      }
      default:
        return `${moduleId} snapshot`
    }
  } catch {
    return `${moduleId} snapshot`
  }
}

// Debounce timers per module
const debounceTimers = {}

export const versionEngine = {
  async snapshot(moduleId, state, label = null, autoGenerated = true) {
    try {
      const json = JSON.stringify(state)
      const stateCompressed = compress(json)
      const snap = {
        id: uuidv4(),
        moduleId,
        timestamp: Date.now(),
        label: label ?? autoLabel(moduleId, state),
        stateCompressed,
        sizeBytes: stateCompressed.length,
        autoGenerated,
      }
      await saveSnapshot(snap)
      return snap
    } catch (err) {
      console.warn('[versionEngine] snapshot failed', err)
    }
  },

  async snapshotDebounced(moduleId, state, delayMs = 1000, label = null) {
    if (debounceTimers[moduleId]) clearTimeout(debounceTimers[moduleId])
    debounceTimers[moduleId] = setTimeout(() => {
      this.snapshot(moduleId, state, label, true)
      delete debounceTimers[moduleId]
    }, delayMs)
  },

  decompressState(stateCompressed) {
    try {
      return JSON.parse(decompress(stateCompressed))
    } catch {
      return null
    }
  },

  async getHistory(moduleId, limit = 50) {
    return getSnapshots(moduleId, limit)
  },

  computeDiff(prevState, currState, moduleId) {
    if (!prevState || !currState) return []
    try {
      switch (moduleId) {
        case 'playground': {
          const diffs = []
          const prev = prevState.parameters ?? {}
          const curr = currState.parameters ?? {}
          for (const k of new Set([...Object.keys(prev), ...Object.keys(curr)])) {
            if (prev[k] !== curr[k]) {
              diffs.push(`${k}: ${prev[k] ?? '—'} → ${curr[k] ?? '—'}`)
            }
          }
          return diffs
        }
        case 'notebook': {
          const prevLen = (prevState.entries ?? []).length
          const currLen = (currState.entries ?? []).length
          const last = (currState.entries ?? [])[currLen - 1]
          const diffs = []
          if (currLen !== prevLen) diffs.push(`${currLen > prevLen ? '+' : ''}${currLen - prevLen} entries`)
          if (last?.title) diffs.push(`Last: ${last.title}`)
          return diffs
        }
        case 'bom': {
          const prevItems = prevState.items ?? []
          const currItems = currState.items ?? []
          const prevCost = prevItems.reduce((s, i) => s + (i.quantity ?? 1) * (i.unitPrice ?? 0), 0)
          const currCost = currItems.reduce((s, i) => s + (i.quantity ?? 1) * (i.unitPrice ?? 0), 0)
          return [
            `Items: ${prevItems.length} → ${currItems.length}`,
            `Cost: $${prevCost.toFixed(2)} → $${currCost.toFixed(2)}`,
          ]
        }
        case 'debug': {
          const prevLines = (prevState.code ?? '').split('\n').length
          const currLines = (currState.code ?? '').split('\n').length
          return [`Lines: ${prevLines} → ${currLines}`]
        }
        default: {
          return ['State updated']
        }
      }
    } catch {
      return ['State updated']
    }
  },
}
