import type { ParamValues, OutputValues, PlaygroundSchema } from './types'

/**
 * Safe formula evaluator.
 * Creates a sandboxed Function with only the parameter names in scope —
 * no access to window, document, globalThis, or any other global.
 */
export function evalFormula(
  formula: string,
  params: ParamValues,
  extraVars: OutputValues = {}
): number | null {
  try {
    const scope = { ...params, ...extraVars, Math }
    const names = Object.keys(scope)
    const values = Object.values(scope)

    // Explicitly block dangerous identifiers
    const blocked = ['window', 'document', 'globalThis', 'self', 'fetch', 'eval', 'Function']
    for (const b of blocked) {
      if (formula.includes(b)) return null
    }

    // eslint-disable-next-line no-new-func
    const fn = new Function(...names, `"use strict"; return (${formula});`)
    const result = fn(...values)

    if (typeof result !== 'number' || !isFinite(result)) return null
    return result
  } catch {
    return null
  }
}

/** Evaluate all equations given current param values, resolving inter-equation dependencies. */
export function evalAll(schema: PlaygroundSchema, params: ParamValues): OutputValues {
  const outputs: OutputValues = {}

  // Up to N passes to resolve dependencies between equations
  for (let pass = 0; pass < schema.equations.length + 1; pass++) {
    for (const eq of schema.equations) {
      if (outputs[eq.outputName] !== undefined) continue
      const val = evalFormula(eq.formula, params, outputs)
      if (val !== null) outputs[eq.outputName] = val
    }
  }

  // Fill remaining unresolved with null
  for (const eq of schema.equations) {
    if (outputs[eq.outputName] === undefined) outputs[eq.outputName] = null
  }

  return outputs
}

/** Sweep one parameter across its range, returning chart data points. */
export function sweepParameter(
  schema: PlaygroundSchema,
  params: ParamValues,
  sweepName: string,
  steps = 120
): Array<Record<string, number | null>> {
  const param = schema.parameters.find((p) => p.name === sweepName)
  if (!param) return []

  const points: Array<Record<string, number | null>> = []

  for (let i = 0; i <= steps; i++) {
    const t = i / steps
    const value = param.min + t * (param.max - param.min)
    const sweptParams = { ...params, [sweepName]: value }
    const outputs = evalAll(schema, sweptParams)
    points.push({ [sweepName]: value, ...outputs })
  }

  return points
}

/** Generate a Python script replicating the playground. */
export function exportPython(
  schema: PlaygroundSchema,
  params: ParamValues,
  sweepName: string
): string {
  const sweepParam = schema.parameters.find((p) => p.name === sweepName)
  if (!sweepParam) return '# No sweep parameter selected'

  const paramLines = schema.parameters
    .map((p) => `${p.name} = ${params[p.name] ?? p.default}  # ${p.label} (${p.unit})`)
    .join('\n')

  // Translate JS math to Python math
  function jsToPython(expr: string): string {
    return expr
      .replace(/Math\.sqrt/g, 'np.sqrt')
      .replace(/Math\.abs/g, 'np.abs')
      .replace(/Math\.pow\(([^,]+),\s*([^)]+)\)/g, '($1 ** $2)')
      .replace(/Math\.exp/g, 'np.exp')
      .replace(/Math\.log/g, 'np.log')
      .replace(/Math\.sin/g, 'np.sin')
      .replace(/Math\.cos/g, 'np.cos')
      .replace(/Math\.PI/g, 'np.pi')
      .replace(/\*\*/g, '**')
  }

  const sweepLine = `${sweepParam.name}_range = np.linspace(${sweepParam.min}, ${sweepParam.max}, 300)  # ${sweepParam.label}`

  const equationLines = schema.equations
    .map((eq) => {
      const pyFormula = jsToPython(eq.formula)
      return `    ${eq.outputName} = ${pyFormula}  # ${eq.label} (${eq.unit})`
    })
    .join('\n')

  const plotLines = schema.equations
    .map((eq) => `    ax.plot(${sweepParam.name}_range, results['${eq.outputName}'], label="${eq.label} (${eq.unit})", color="${eq.color}")`)
    .join('\n')

  return `#!/usr/bin/env python3
"""
Generated by Enginguity — Parameter Playground
"""
import numpy as np
import matplotlib.pyplot as plt

# ── Fixed parameters ──────────────────────────────────────────────────────────
${paramLines}

# ── Sweep ─────────────────────────────────────────────────────────────────────
${sweepLine}

results = {eq: [] for eq in [${schema.equations.map((e) => `"${e.outputName}"`).join(', ')}]}

for ${sweepParam.name} in ${sweepParam.name}_range:
${equationLines}
${schema.equations.map((eq) => `    results["${eq.outputName}"].append(${eq.outputName})`).join('\n')}

# ── Plot ──────────────────────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(10, 6))
fig.patch.set_facecolor("#13131f")
ax.set_facecolor("#080810")
ax.tick_params(colors="#6b6d85")
ax.spines[:].set_color("#1f1f35")
ax.set_xlabel("${sweepParam.label} (${sweepParam.unit})", color="#6b6d85")
ax.set_title("Parameter Sweep — ${sweepParam.label}", color="#e2e4f0", pad=12)

${plotLines}

ax.legend(facecolor="#13131f", edgecolor="#1f1f35", labelcolor="#e2e4f0")
plt.tight_layout()
plt.show()
`
}
