import { useState, useCallback, useEffect, useRef } from 'react'
import { versionEngine } from '../engine/versionEngine.js'
import { logEvent } from '../engine/eventLog'

export function useVersionHistory(moduleId, restoreState) {
  const [panelOpen, setPanelOpen] = useState(false)
  const snapshotRef = useRef(versionEngine.snapshot.bind(versionEngine))

  const snapshot = useCallback(
    (state, label = null, autoGenerated = true) =>
      versionEngine.snapshot(moduleId, state, label, autoGenerated),
    [moduleId]
  )

  const snapshotDebounced = useCallback(
    (state, delayMs = 1000, label = null) =>
      versionEngine.snapshotDebounced(moduleId, state, delayMs, label),
    [moduleId]
  )

  const restore = useCallback(
    async (snap, getCurrentState) => {
      // Save current state first
      if (getCurrentState) {
        const current = getCurrentState()
        await versionEngine.snapshot(moduleId, current, 'Before restore', false)
      }
      const state = versionEngine.decompressState(snap.stateCompressed)
      if (state && restoreState) {
        restoreState(state)
        logEvent('VERSION_RESTORED', {
          moduleId,
          versionId: snap.id,
          label: snap.label,
          module: moduleId
        })
      }
      return state
    },
    [moduleId, restoreState]
  )

  return { panelOpen, setPanelOpen, snapshot, snapshotDebounced, restore }
}
