import { useState, useEffect, useCallback } from 'react'
import { Clock, Search, Download, X, RotateCcw, Filter } from 'lucide-react'
import { getAllSnapshots, clearAutoSnapshots } from '../../engine/db.js'
import { versionEngine } from '../../engine/versionEngine.js'
import { useProbeContext } from '../../hooks/useProbeContext'

const MODULE_LABELS = {
  playground: 'Parameter Playground',
  notebook: 'Notebook',
  bom: 'BOM Intelligence',
  debug: 'Debug Console',
  brain: 'Project Brain',
  cad: 'CAD Viewer',
}

function formatDate(ts) {
  return new Date(ts).toLocaleDateString([], { month: 'short', day: 'numeric', year: 'numeric' })
}

function formatTime(ts) {
  return new Date(ts).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
}

function formatBytes(n) {
  if (n < 1024) return `${n}B`
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)}KB`
  return `${(n / 1024 / 1024).toFixed(2)}MB`
}

export function HistoryPage() {
  const [snapshots, setSnapshots] = useState([])
  const [search, setSearch] = useState('')
  const [moduleFilter, setModuleFilter] = useState([])
  const [loading, setLoading] = useState(true)
  const [totalSize, setTotalSize] = useState(0)
  const [clearConfirm, setClearConfirm] = useState(false)

  useProbeContext('history', {
    snapshotCount: snapshots.length,
    totalSizeBytes: totalSize,
    search: search || null,
    moduleFilters: moduleFilter,
  })

  const load = useCallback(async () => {
    setLoading(true)
    const all = await getAllSnapshots()
    setSnapshots(all)
    setTotalSize(all.reduce((s, snap) => s + (snap.sizeBytes ?? 0), 0))
    setLoading(false)
  }, [])

  useEffect(() => { load() }, [load])

  const allModules = [...new Set(snapshots.map(s => s.moduleId))]

  const filtered = snapshots.filter(snap => {
    if (moduleFilter.length > 0 && !moduleFilter.includes(snap.moduleId)) return false
    if (search && !snap.label?.toLowerCase().includes(search.toLowerCase())) return false
    return true
  })

  // Group by module then date
  const byModule = {}
  for (const snap of filtered) {
    const mod = snap.moduleId
    if (!byModule[mod]) byModule[mod] = []
    byModule[mod].push(snap)
  }

  const autoCount = snapshots.filter(s => s.autoGenerated).length

  const handleClear = async () => {
    if (!clearConfirm) { setClearConfirm(true); return }
    await clearAutoSnapshots()
    setClearConfirm(false)
    load()
  }

  const handleExport = () => {
    const json = JSON.stringify(snapshots, null, 2)
    const blob = new Blob([json], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `enginguity_history_${Date.now()}.json`
    a.click()
    URL.revokeObjectURL(url)
  }

  const toggleModule = (mod) => {
    setModuleFilter(prev =>
      prev.includes(mod) ? prev.filter(m => m !== mod) : [...prev, mod]
    )
  }

  return (
    <div style={{ height: '100%', display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
      {/* Header */}
      <div style={{
        padding: '16px 24px 14px',
        borderBottom: '1px solid var(--border)',
        flexShrink: 0,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 16,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <Clock size={18} style={{ color: 'var(--text-muted)' }} />
          <span style={{ fontSize: 16, fontWeight: 500, color: 'var(--text)' }}>Version History</span>
          <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: 'var(--text-dim)' }}>
            {snapshots.length} snapshots · {formatBytes(totalSize)}
          </span>
        </div>

        <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
          {clearConfirm ? (
            <>
              <span style={{ fontSize: 12, color: 'var(--text-muted)' }}>
                Clear {autoCount} auto-generated snapshots?
              </span>
              <button onClick={handleClear} style={actionBtn('#b08080')}>Clear</button>
              <button onClick={() => setClearConfirm(false)} style={actionBtn('var(--border-bright)')}>Cancel</button>
            </>
          ) : (
            <button onClick={() => setClearConfirm(true)} style={actionBtn('var(--border-bright)', 'var(--text-muted)')}>
              Clear auto-snapshots
            </button>
          )}
          <button onClick={handleExport} style={{ ...actionBtn('var(--border-bright)', 'var(--text-muted)'), display: 'flex', alignItems: 'center', gap: 5 }}>
            <Download size={12} /> Export JSON
          </button>
        </div>
      </div>

      {/* Search + module filter */}
      <div style={{ padding: '12px 24px', borderBottom: '1px solid var(--border)', flexShrink: 0 }}>
        <div style={{ position: 'relative', marginBottom: 10 }}>
          <Search size={13} style={{ position: 'absolute', left: 10, top: '50%', transform: 'translateY(-50%)', color: 'var(--text-dim)' }} />
          <input
            value={search}
            onChange={e => setSearch(e.target.value)}
            placeholder="Search snapshots..."
            style={{
              width: '100%',
              paddingLeft: 32,
              paddingRight: 12,
              height: 34,
              fontSize: 14,
              background: 'var(--surface-2)',
              border: '1px solid var(--border)',
              borderRadius: 6,
              color: 'var(--text)',
              outline: 'none',
              boxSizing: 'border-box',
            }}
          />
        </div>

        <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
          {allModules.map(mod => {
            const active = moduleFilter.includes(mod)
            return (
              <label key={mod} style={{ display: 'flex', alignItems: 'center', gap: 5, cursor: 'pointer' }}>
                <input
                  type="checkbox"
                  checked={active}
                  onChange={() => toggleModule(mod)}
                  style={{ accentColor: 'var(--accent)' }}
                />
                <span style={{ fontSize: 12, color: active ? 'var(--text)' : 'var(--text-muted)' }}>
                  {MODULE_LABELS[mod] ?? mod}
                </span>
              </label>
            )
          })}
        </div>
      </div>

      {/* Content */}
      <div style={{ flex: 1, overflowY: 'auto', padding: '16px 24px' }}>
        {loading ? (
          <div style={{ fontSize: 13, color: 'var(--text-dim)' }}>Loading...</div>
        ) : filtered.length === 0 ? (
          <div style={{ fontSize: 13, color: 'var(--text-dim)' }}>
            No snapshots found. Use a module to start building history.
          </div>
        ) : (
          Object.entries(byModule).map(([mod, snaps]) => (
            <div key={mod} style={{ marginBottom: 32 }}>
              <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 10, fontWeight: 500 }}>
                {MODULE_LABELS[mod] ?? mod}
                <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: 'var(--text-dim)', marginLeft: 8 }}>
                  {snaps.length} snapshots
                </span>
              </div>

              {snaps.map((snap, i) => {
                const prev = snaps[i + 1] ?? null
                return (
                  <HistoryRow key={snap.id} snap={snap} prev={prev} moduleId={mod} onRefresh={load} />
                )
              })}
            </div>
          ))
        )}
      </div>
    </div>
  )
}

function HistoryRow({ snap, prev, moduleId, onRefresh }) {
  const [hovered, setHovered] = useState(false)

  const diff = prev
    ? versionEngine.computeDiff(
        versionEngine.decompressState(prev.stateCompressed),
        versionEngine.decompressState(snap.stateCompressed),
        moduleId
      )
    : []

  return (
    <div
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      style={{
        display: 'flex',
        alignItems: 'flex-start',
        gap: 12,
        padding: '10px 12px',
        borderRadius: 6,
        background: hovered ? 'var(--surface-2)' : 'transparent',
        marginBottom: 2,
        transition: 'background 120ms',
      }}
    >
      <div style={{ flexShrink: 0, paddingTop: 2 }}>
        <div style={{
          width: 7,
          height: 7,
          borderRadius: '50%',
          background: snap.autoGenerated ? 'var(--border-bright)' : 'var(--accent)',
          marginTop: 4,
        }} />
      </div>

      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ fontSize: 13, color: snap.autoGenerated ? 'var(--text-muted)' : 'var(--text)', marginBottom: 2 }}>
          {snap.label}
        </div>
        {diff.length > 0 && (
          <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
            {diff.map((d, i) => (
              <span key={i} style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: 'var(--text-dim)' }}>
                {d}
              </span>
            ))}
          </div>
        )}
      </div>

      <div style={{ flexShrink: 0, textAlign: 'right' }}>
        <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: 'var(--text-dim)' }}>
          {formatDate(snap.timestamp)}
        </div>
        <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: 'var(--text-dim)' }}>
          {formatTime(snap.timestamp)}
        </div>
        <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: 'var(--text-dim)', marginTop: 2 }}>
          {formatBytes(snap.sizeBytes ?? 0)}
        </div>
      </div>
    </div>
  )
}

function actionBtn(borderColor, color = 'var(--text)') {
  return {
    fontSize: 12,
    padding: '5px 12px',
    borderRadius: 5,
    background: 'transparent',
    border: `1px solid ${borderColor}`,
    color,
    cursor: 'pointer',
  }
}
