export const CERTIFICATIONS_DB = {
  FCC_Part15: {
    name: 'FCC Part 15',
    full_name: 'FCC Part 15 — Unintentional Radiators',
    region: 'United States',
    applies_to: ['consumer electronics', 'IoT', 'computing devices'],
    self_certify: true,
    lab_required: true,
    cost_range: [5000, 15000],
    timeline_weeks: [4, 12],
    governing_body: 'Federal Communications Commission',
    website: 'https://www.fcc.gov',
  },
  FCC_Part22_24: {
    name: 'FCC ID',
    full_name: 'FCC ID — Intentional Radiators (Part 22/24/27)',
    region: 'United States',
    applies_to: ['RF transmitters', 'WiFi', 'Bluetooth', 'cellular', 'LoRa'],
    self_certify: false,
    lab_required: true,
    cost_range: [8000, 25000],
    timeline_weeks: [6, 16],
    governing_body: 'Federal Communications Commission',
    website: 'https://www.fcc.gov',
  },
  CE_Marking: {
    name: 'CE Marking',
    full_name: 'CE Marking — European Conformity',
    region: 'European Union',
    applies_to: ['all products sold in EU'],
    self_certify: true,
    lab_required: false,
    cost_range: [3000, 30000],
    timeline_weeks: [8, 24],
    governing_body: 'European Commission',
    website: 'https://ec.europa.eu/growth/single-market/ce-marking',
  },
  RED_Directive: {
    name: 'RED',
    full_name: 'Radio Equipment Directive 2014/53/EU',
    region: 'European Union',
    applies_to: ['RF transmitters', 'WiFi', 'Bluetooth', 'cellular'],
    self_certify: false,
    lab_required: true,
    cost_range: [5000, 20000],
    timeline_weeks: [8, 20],
    governing_body: 'European Commission',
    website: 'https://ec.europa.eu',
  },
  UKCA: {
    name: 'UKCA',
    full_name: 'UK Conformity Assessed',
    region: 'United Kingdom',
    applies_to: ['all products sold in Great Britain'],
    self_certify: true,
    lab_required: false,
    cost_range: [2000, 15000],
    timeline_weeks: [6, 20],
    governing_body: 'Office for Product Safety and Standards',
    website: 'https://www.gov.uk/ukca',
  },
  UL_Listed: {
    name: 'UL Listing',
    full_name: 'UL Listing — Safety Certification',
    region: 'United States',
    applies_to: ['mains-powered products', 'power supplies', 'industrial equipment'],
    self_certify: false,
    lab_required: true,
    cost_range: [8000, 50000],
    timeline_weeks: [12, 52],
    governing_body: 'UL Standards & Engagement',
    website: 'https://ul.com',
  },
  IC_ID: {
    name: 'IC ID',
    full_name: 'Innovation, Science and Economic Development Canada',
    region: 'Canada',
    applies_to: ['RF transmitters', 'radio devices'],
    self_certify: false,
    lab_required: true,
    cost_range: [4000, 12000],
    timeline_weeks: [4, 10],
    governing_body: 'ISED Canada',
    website: 'https://www.ic.gc.ca',
  },
  RCM: {
    name: 'RCM',
    full_name: 'Regulatory Compliance Mark (Australia/NZ)',
    region: 'Australia',
    applies_to: ['electrical products', 'consumer electronics', 'RF devices'],
    self_certify: true,
    lab_required: true,
    cost_range: [5000, 20000],
    timeline_weeks: [6, 16],
    governing_body: 'ACMA / Energy Safe Australia',
    website: 'https://www.acma.gov.au',
  },
  TELEC: {
    name: 'TELEC',
    full_name: 'Telecommunications Equipment Certification — Japan',
    region: 'Japan',
    applies_to: ['RF transmitters', 'radio equipment'],
    self_certify: false,
    lab_required: true,
    cost_range: [6000, 18000],
    timeline_weeks: [8, 20],
    governing_body: 'Ministry of Internal Affairs and Communications',
    website: 'https://www.tele.soumu.go.jp',
  },
  KC_Mark: {
    name: 'KC Mark',
    full_name: 'Korea Certification',
    region: 'South Korea',
    applies_to: ['RF devices', 'consumer electronics', 'electrical products'],
    self_certify: false,
    lab_required: true,
    cost_range: [5000, 15000],
    timeline_weeks: [6, 14],
    governing_body: 'National Radio Research Agency',
    website: 'https://www.nrra.go.kr',
  },
  SRRC: {
    name: 'SRRC',
    full_name: 'State Radio Regulation of China',
    region: 'China',
    applies_to: ['RF transmitters', 'wireless devices'],
    self_certify: false,
    lab_required: true,
    cost_range: [4000, 12000],
    timeline_weeks: [8, 16],
    governing_body: 'State Radio Regulation Commission',
    website: 'https://www.srrc.org.cn',
  },
  CCC: {
    name: 'CCC',
    full_name: 'China Compulsory Certificate',
    region: 'China',
    applies_to: ['consumer electronics', 'electrical products', 'IT equipment'],
    self_certify: false,
    lab_required: true,
    cost_range: [5000, 20000],
    timeline_weeks: [10, 24],
    governing_body: 'Certification and Accreditation Administration of China',
    website: 'https://www.cnca.gov.cn',
  },
  ANATEL: {
    name: 'ANATEL',
    full_name: 'Brazilian RF/Electrical Certification',
    region: 'Brazil',
    applies_to: ['RF devices', 'telecom equipment', 'consumer electronics'],
    self_certify: false,
    lab_required: true,
    cost_range: [6000, 20000],
    timeline_weeks: [10, 24],
    governing_body: 'Agência Nacional de Telecomunicações',
    website: 'https://www.gov.br/anatel',
  },
  BIS: {
    name: 'BIS',
    full_name: 'Bureau of Indian Standards Certification',
    region: 'India',
    applies_to: ['electronics', 'IT products', 'electrical equipment'],
    self_certify: false,
    lab_required: true,
    cost_range: [5000, 18000],
    timeline_weeks: [12, 30],
    governing_body: 'Bureau of Indian Standards',
    website: 'https://www.bis.gov.in',
  },
  IEC_62368: {
    name: 'IEC 62368-1',
    full_name: 'IEC 62368-1 — Audio/Video, IT and Comm Equipment Safety',
    region: 'Global',
    applies_to: ['consumer electronics', 'IT equipment', 'AV equipment'],
    self_certify: false,
    lab_required: true,
    cost_range: [4000, 20000],
    timeline_weeks: [8, 24],
    governing_body: 'IEC',
    website: 'https://www.iec.ch',
  },
  IEC_60950: {
    name: 'IEC 60950-1',
    full_name: 'IEC 60950-1 — Information Technology Equipment Safety (Legacy)',
    region: 'Global',
    applies_to: ['IT equipment', 'mains-powered devices'],
    self_certify: false,
    lab_required: true,
    cost_range: [4000, 18000],
    timeline_weeks: [8, 20],
    governing_body: 'IEC',
    website: 'https://www.iec.ch',
  },
  MDD_MDR: {
    name: 'MDR / CE Medical',
    full_name: 'EU Medical Device Regulation 2017/745',
    region: 'European Union',
    applies_to: ['medical devices', 'body-contact devices'],
    self_certify: false,
    lab_required: true,
    cost_range: [50000, 500000],
    timeline_weeks: [52, 260],
    governing_body: 'European Commission / Notified Bodies',
    website: 'https://ec.europa.eu/health/md_sector',
  },
  FDA_510k: {
    name: 'FDA 510(k)',
    full_name: 'FDA 510(k) Premarket Notification — Medical Devices',
    region: 'United States',
    applies_to: ['medical devices', 'Class II devices'],
    self_certify: false,
    lab_required: true,
    cost_range: [30000, 300000],
    timeline_weeks: [52, 208],
    governing_body: 'U.S. Food and Drug Administration',
    website: 'https://www.fda.gov/medical-devices',
  },
  ROHS: {
    name: 'RoHS',
    full_name: 'Restriction of Hazardous Substances Directive',
    region: 'European Union',
    applies_to: ['all electronic equipment sold in EU'],
    self_certify: true,
    lab_required: false,
    cost_range: [500, 5000],
    timeline_weeks: [2, 8],
    governing_body: 'European Commission',
    website: 'https://ec.europa.eu/environment/topics/waste-and-recycling/rohs-directive',
  },
  WEEE: {
    name: 'WEEE',
    full_name: 'Waste Electrical and Electronic Equipment Directive',
    region: 'European Union',
    applies_to: ['all electrical/electronic equipment sold in EU'],
    self_certify: true,
    lab_required: false,
    cost_range: [500, 3000],
    timeline_weeks: [2, 6],
    governing_body: 'European Commission',
    website: 'https://ec.europa.eu/environment/topics/waste-and-recycling/waste-electrical-and-electronic-equipment-weee',
  },
}
