const MODEL_REGISTRY = {
  anthropic: {
    name: 'Anthropic',
    color: '#cc785c',
    keyPrefix: 'sk-ant-',
    docsUrl: 'https://console.anthropic.com/keys',
    baseURL: 'https://api.anthropic.com/v1',
    authHeader: 'x-api-key',
    models: [
      { id: 'claude-opus-4-5', name: 'Claude Opus 4.5', tier: 'flagship', context: '200K' },
      { id: 'claude-sonnet-4-5', name: 'Claude Sonnet 4.5', tier: 'balanced', context: '200K' },
      { id: 'claude-haiku-4-5', name: 'Claude Haiku 4.5', tier: 'fast', context: '200K' },
    ],
  },
  openai: {
    name: 'OpenAI',
    color: '#10a37f',
    keyPrefix: 'sk-',
    docsUrl: 'https://platform.openai.com/api-keys',
    baseURL: 'https://api.openai.com/v1',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    models: [
      { id: 'gpt-4o', name: 'GPT-4o', tier: 'flagship', context: '128K' },
      { id: 'gpt-4o-mini', name: 'GPT-4o Mini', tier: 'fast', context: '128K' },
      { id: 'gpt-4-turbo', name: 'GPT-4 Turbo', tier: 'balanced', context: '128K' },
      { id: 'o1', name: 'o1', tier: 'reasoning', context: '200K' },
      { id: 'o1-mini', name: 'o1 Mini', tier: 'reasoning', context: '128K' },
      { id: 'o3-mini', name: 'o3 Mini', tier: 'reasoning', context: '200K' },
    ],
  },
  google: {
    name: 'Google',
    color: '#7a9ab8',
    keyPrefix: 'AIza',
    docsUrl: 'https://aistudio.google.com/apikey',
    baseURL: 'https://generativelanguage.googleapis.com/v1beta',
    authHeader: 'x-goog-api-key',
    models: [
      { id: 'gemini-2.0-flash', name: 'Gemini 2.0 Flash', tier: 'fast', context: '1M' },
      { id: 'gemini-2.0-flash-thinking-exp', name: 'Gemini 2.0 Flash Thinking', tier: 'reasoning', context: '1M' },
      { id: 'gemini-1.5-pro', name: 'Gemini 1.5 Pro', tier: 'flagship', context: '2M' },
      { id: 'gemini-1.5-flash', name: 'Gemini 1.5 Flash', tier: 'fast', context: '1M' },
      { id: 'gemini-1.5-flash-8b', name: 'Gemini 1.5 Flash 8B', tier: 'fast', context: '1M' },
    ],
  },
  deepseek: {
    name: 'DeepSeek',
    color: '#7a85b8',
    keyPrefix: 'sk-',
    docsUrl: 'https://platform.deepseek.com/api_keys',
    baseURL: 'https://api.deepseek.com/v1',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    models: [
      { id: 'deepseek-chat', name: 'DeepSeek V3', tier: 'flagship', context: '64K' },
      { id: 'deepseek-reasoner', name: 'DeepSeek R1', tier: 'reasoning', context: '64K' },
    ],
  },
  xai: {
    name: 'xAI',
    color: '#ffffff',
    keyPrefix: 'xai-',
    docsUrl: 'https://console.x.ai',
    baseURL: 'https://api.x.ai/v1',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    models: [
      { id: 'grok-3', name: 'Grok 3', tier: 'flagship', context: '131K' },
      { id: 'grok-3-fast', name: 'Grok 3 Fast', tier: 'fast', context: '131K' },
      { id: 'grok-3-mini', name: 'Grok 3 Mini', tier: 'reasoning', context: '131K' },
      { id: 'grok-2-vision-1212', name: 'Grok 2 Vision', tier: 'balanced', context: '32K' },
    ],
  },
  mistral: {
    name: 'Mistral',
    color: '#ff7000',
    keyPrefix: '',
    docsUrl: 'https://console.mistral.ai/api-keys',
    baseURL: 'https://api.mistral.ai/v1',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    models: [
      { id: 'mistral-large-latest', name: 'Mistral Large', tier: 'flagship', context: '128K' },
      { id: 'mistral-medium-latest', name: 'Mistral Medium', tier: 'balanced', context: '128K' },
      { id: 'mistral-small-latest', name: 'Mistral Small', tier: 'fast', context: '128K' },
      { id: 'codestral-latest', name: 'Codestral', tier: 'code', context: '256K' },
      { id: 'open-mistral-7b', name: 'Mistral 7B', tier: 'fast', context: '32K' },
    ],
  },
  qwen: {
    name: 'Alibaba',
    color: '#b07e50',
    keyPrefix: 'sk-',
    docsUrl: 'https://dashscope.aliyuncs.com',
    baseURL: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    note: 'Uses the international (intl) endpoint. Keys from DashScope console.',
    models: [
      { id: 'qwen-max', name: 'Qwen Max', tier: 'flagship', context: '32K' },
      { id: 'qwen-plus', name: 'Qwen Plus', tier: 'balanced', context: '128K' },
      { id: 'qwen-turbo', name: 'Qwen Turbo', tier: 'fast', context: '1M' },
      { id: 'qwq-32b', name: 'QwQ 32B', tier: 'reasoning', context: '32K' },
      { id: 'qwen-coder-plus', name: 'Qwen Coder Plus', tier: 'code', context: '128K' },
    ],
  },
  cohere: {
    name: 'Cohere',
    color: '#39594d',
    keyPrefix: '',
    docsUrl: 'https://dashboard.cohere.com/api-keys',
    baseURL: 'https://api.cohere.com/v2',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    models: [
      { id: 'command-r-plus-08-2024', name: 'Command R+', tier: 'flagship', context: '128K' },
      { id: 'command-r-08-2024', name: 'Command R', tier: 'balanced', context: '128K' },
      { id: 'command-a-03-2025', name: 'Command A', tier: 'flagship', context: '256K' },
    ],
  },
  groq: {
    name: 'Groq',
    color: '#b07070',
    keyPrefix: 'gsk_',
    docsUrl: 'https://console.groq.com/keys',
    baseURL: 'https://api.groq.com/openai/v1',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    models: [
      { id: 'llama-3.3-70b-versatile', name: 'Llama 3.3 70B', tier: 'flagship', context: '128K' },
      { id: 'llama-3.1-8b-instant', name: 'Llama 3.1 8B', tier: 'fast', context: '128K' },
      { id: 'mixtral-8x7b-32768', name: 'Mixtral 8x7B', tier: 'balanced', context: '32K' },
      { id: 'gemma2-9b-it', name: 'Gemma 2 9B', tier: 'fast', context: '8K' },
      { id: 'deepseek-r1-distill-llama-70b', name: 'DeepSeek R1 Distill 70B', tier: 'reasoning', context: '128K' },
    ],
  },
  openrouter: {
    name: 'OpenRouter',
    color: '#8a85b8',
    keyPrefix: 'sk-or-',
    docsUrl: 'https://openrouter.ai/keys',
    baseURL: 'https://openrouter.ai/api/v1',
    authHeader: 'Authorization',
    authPrefix: 'Bearer ',
    note: 'Access 200+ models through one key',
    models: [
      { id: 'meta-llama/llama-3.3-70b-instruct', name: 'Llama 3.3 70B', tier: 'flagship', context: '128K' },
      { id: 'nousresearch/hermes-3-llama-3.1-405b', name: 'Hermes 3 405B', tier: 'flagship', context: '128K' },
      { id: 'perplexity/llama-3.1-sonar-huge-128k-online', name: 'Perplexity Sonar Huge', tier: 'flagship', context: '128K' },
      { id: 'microsoft/phi-4', name: 'Phi-4', tier: 'fast', context: '16K' },
    ],
  },
}

export default MODEL_REGISTRY
