import { useState, useEffect, useCallback, useRef } from 'react'
import { Clock, X, RotateCcw, Bookmark, ChevronDown, ChevronUp } from 'lucide-react'
import { versionEngine } from '../../engine/versionEngine.js'
import { updateSnapshot } from '../../engine/db.js'

const MODULE_LABELS = {
  playground: 'Parameter Playground',
  notebook: 'Notebook',
  bom: 'BOM Intelligence',
  debug: 'Debug Console',
  brain: 'Project Brain',
  cad: 'CAD Viewer',
}

function formatTime(ts) {
  const now = Date.now()
  const diff = now - ts
  if (diff < 60000) return 'just now'
  if (diff < 3600000) return `${Math.floor(diff / 60000)}m ago`
  if (diff < 86400000) return `${Math.floor(diff / 3600000)}h ago`
  return new Date(ts).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
}

function formatDateGroup(ts) {
  const d = new Date(ts)
  const today = new Date()
  const yesterday = new Date(today)
  yesterday.setDate(today.getDate() - 1)
  if (d.toDateString() === today.toDateString()) return 'Today'
  if (d.toDateString() === yesterday.toDateString()) return 'Yesterday'
  return d.toLocaleDateString([], { month: 'long', day: 'numeric' })
}

function groupByDate(snapshots) {
  const groups = {}
  for (const snap of snapshots) {
    const label = formatDateGroup(snap.timestamp)
    if (!groups[label]) groups[label] = []
    groups[label].push(snap)
  }
  return groups
}

function SnapshotEntry({ snap, prevSnap, moduleId, onRestore, onRefresh, isFirst }) {
  const [expanded, setExpanded] = useState(false)
  const [confirming, setConfirming] = useState(false)
  const [naming, setNaming] = useState(false)
  const [nameInput, setNameInput] = useState('')
  const [hovered, setHovered] = useState(false)
  const nameRef = useRef(null)

  const diff = prevSnap
    ? versionEngine.computeDiff(
        versionEngine.decompressState(prevSnap.stateCompressed),
        versionEngine.decompressState(snap.stateCompressed),
        moduleId
      )
    : []

  const handleSaveName = async () => {
    if (!nameInput.trim()) return
    await updateSnapshot(snap.id, { label: nameInput.trim(), autoGenerated: false })
    setNaming(false)
    setNameInput('')
    onRefresh()
  }

  const handleRestore = async () => {
    if (!confirming) { setConfirming(true); return }
    setConfirming(false)
    await onRestore(snap)
  }

  return (
    <div style={{ position: 'relative', paddingLeft: 16 }}>
      {/* Timeline line */}
      <div style={{
        position: 'absolute',
        left: 7,
        top: 0,
        bottom: 0,
        width: 1,
        background: 'var(--border)',
      }} />

      {/* Dot */}
      <div style={{
        position: 'absolute',
        left: 4,
        top: 22,
        width: 7,
        height: 7,
        borderRadius: '50%',
        background: isFirst ? 'var(--accent)' : 'var(--border-bright)',
        zIndex: 1,
      }} />

      {/* Entry row */}
      <div
        onClick={() => setExpanded(!expanded)}
        onMouseEnter={() => setHovered(true)}
        onMouseLeave={() => setHovered(false)}
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          height: 48,
          padding: '0 8px',
          borderRadius: 6,
          cursor: 'pointer',
          background: hovered ? 'var(--surface-2)' : 'transparent',
          transition: 'background 120ms',
          userSelect: 'none',
        }}
      >
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{
            fontSize: 13,
            color: snap.autoGenerated ? 'var(--text-muted)' : 'var(--text)',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            whiteSpace: 'nowrap',
          }}>
            {snap.label}
            {isFirst && (
              <span style={{ fontSize: 10, fontStyle: 'italic', color: 'var(--text-dim)', marginLeft: 6 }}>
                current
              </span>
            )}
          </div>
          <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: 'var(--text-dim)' }}>
            {formatTime(snap.timestamp)}
          </div>
        </div>

        {hovered && (
          <div style={{ display: 'flex', gap: 4, flexShrink: 0 }}>
            <button
              onClick={(e) => { e.stopPropagation(); setNaming(!naming) }}
              title="Pin / name"
              style={{ background: 'none', border: 'none', color: snap.autoGenerated ? 'var(--text-dim)' : 'var(--accent)', cursor: 'pointer', padding: 2 }}
            >
              <Bookmark size={13} />
            </button>
            <button
              onClick={(e) => { e.stopPropagation(); handleRestore() }}
              title="Restore"
              style={{ background: 'none', border: 'none', color: 'var(--text-dim)', cursor: 'pointer', padding: 2 }}
            >
              <RotateCcw size={13} />
            </button>
          </div>
        )}

        {expanded ? <ChevronUp size={11} style={{ color: 'var(--text-dim)', flexShrink: 0 }} />
                  : <ChevronDown size={11} style={{ color: 'var(--text-dim)', flexShrink: 0 }} />}
      </div>

      {/* Expanded detail */}
      {expanded && (
        <div style={{
          background: 'var(--bg-2)',
          borderRadius: 6,
          padding: 10,
          margin: '4px 0 4px 4px',
        }}>
          {diff.length > 0 ? (
            <div style={{ marginBottom: 8 }}>
              {diff.map((line, i) => (
                <div key={i} style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: 'var(--text-muted)', marginBottom: 2 }}>
                  → {line}
                </div>
              ))}
            </div>
          ) : (
            <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: 'var(--text-dim)', marginBottom: 8 }}>
              (first snapshot)
            </div>
          )}

          {confirming ? (
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
              <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>
                Restore? Current state will be saved first.
              </span>
              <button onClick={handleRestore} style={btnStyle('accent')}>Restore</button>
              <button onClick={() => setConfirming(false)} style={btnStyle('muted')}>Cancel</button>
            </div>
          ) : (
            <button onClick={() => setConfirming(true)} style={btnStyle('accent')}>
              Restore this version
            </button>
          )}

          {naming ? (
            <div style={{ marginTop: 8, display: 'flex', gap: 6 }}>
              <input
                ref={nameRef}
                autoFocus
                value={nameInput}
                onChange={e => setNameInput(e.target.value)}
                onKeyDown={e => { if (e.key === 'Enter') handleSaveName(); if (e.key === 'Escape') setNaming(false) }}
                placeholder="Describe this state..."
                style={{
                  flex: 1,
                  fontSize: 12,
                  background: 'var(--surface)',
                  border: '1px solid var(--border-bright)',
                  borderRadius: 4,
                  padding: '4px 8px',
                  color: 'var(--text)',
                  outline: 'none',
                }}
              />
              <button onClick={handleSaveName} style={btnStyle('accent')}>Save</button>
            </div>
          ) : (
            <button
              onClick={() => setNaming(true)}
              style={{ background: 'none', border: 'none', fontSize: 11, color: 'var(--text-dim)', cursor: 'pointer', marginTop: 6, padding: 0, textDecoration: 'underline' }}
            >
              Name this snapshot
            </button>
          )}
        </div>
      )}
    </div>
  )
}

function btnStyle(variant) {
  if (variant === 'accent') return {
    fontSize: 11,
    padding: '3px 10px',
    borderRadius: 4,
    background: 'transparent',
    border: '1px solid var(--accent)',
    color: 'var(--accent)',
    cursor: 'pointer',
  }
  return {
    fontSize: 11,
    padding: '3px 10px',
    borderRadius: 4,
    background: 'transparent',
    border: '1px solid var(--border)',
    color: 'var(--text-muted)',
    cursor: 'pointer',
  }
}

export function VersionHistoryPanel({ moduleId, onRestore, onClose }) {
  const [snapshots, setSnapshots] = useState([])
  const [filter, setFilter] = useState('all') // 'all' | 'named' | 'today'
  const [loading, setLoading] = useState(true)

  const load = useCallback(async () => {
    setLoading(true)
    const snaps = await versionEngine.getHistory(moduleId, 100)
    setSnapshots(snaps)
    setLoading(false)
  }, [moduleId])

  useEffect(() => { load() }, [load])

  const filtered = snapshots.filter(s => {
    if (filter === 'named') return !s.autoGenerated
    if (filter === 'today') {
      const today = new Date().toDateString()
      return new Date(s.timestamp).toDateString() === today
    }
    return true
  })

  const groups = groupByDate(filtered)

  return (
    <div
      style={{
        position: 'fixed',
        top: 0,
        right: 0,
        width: 280,
        height: '100vh',
        background: 'var(--surface)',
        borderLeft: '1px solid var(--border)',
        zIndex: 200,
        display: 'flex',
        flexDirection: 'column',
        transform: 'translateX(0)',
        animation: 'slideInRight 200ms ease',
        boxShadow: '-4px 0 24px rgba(0,0,0,0.4)',
      }}
    >
      <style>{`
        @keyframes slideInRight {
          from { transform: translateX(100%) }
          to   { transform: translateX(0) }
        }
      `}</style>

      {/* Header */}
      <div style={{ padding: '14px 14px 10px', borderBottom: '1px solid var(--border)', flexShrink: 0 }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div>
            <div style={{ fontSize: 14, color: 'var(--text)', fontWeight: 500 }}>History</div>
            <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>{MODULE_LABELS[moduleId] ?? moduleId}</div>
          </div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', color: 'var(--text-dim)', cursor: 'pointer', padding: 2 }} data-tooltip="Close">
            <X size={15} />
          </button>
        </div>

        {/* Filter pills */}
        <div style={{ display: 'flex', gap: 6, marginTop: 10 }}>
          {['all', 'named', 'today'].map(f => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              style={{
                fontSize: 11,
                padding: '3px 10px',
                borderRadius: 20,
                background: filter === f ? 'var(--surface-2)' : 'transparent',
                border: `1px solid ${filter === f ? 'var(--border-bright)' : 'var(--border)'}`,
                color: filter === f ? 'var(--text)' : 'var(--text-dim)',
                cursor: 'pointer',
                textTransform: 'capitalize',
              }}
            >
              {f}
            </button>
          ))}
        </div>
      </div>

      {/* Timeline */}
      <div style={{ flex: 1, overflowY: 'auto', padding: '8px 10px' }}>
        {loading ? (
          <div style={{ fontSize: 12, color: 'var(--text-dim)', padding: 16 }}>Loading...</div>
        ) : filtered.length === 0 ? (
          <div style={{ fontSize: 12, color: 'var(--text-dim)', padding: 16 }}>No snapshots yet.</div>
        ) : (
          Object.entries(groups).map(([date, snaps]) => (
            <div key={date}>
              <div style={{ fontSize: 11, color: 'var(--text-dim)', padding: '10px 8px 4px', fontWeight: 400 }}>
                {date}
              </div>
              {snaps.map((snap, i) => {
                const globalIdx = filtered.indexOf(snap)
                const prev = filtered[globalIdx + 1] ?? null
                return (
                  <SnapshotEntry
                    key={snap.id}
                    snap={snap}
                    prevSnap={prev}
                    moduleId={moduleId}
                    onRestore={onRestore}
                    onRefresh={load}
                    isFirst={globalIdx === 0}
                  />
                )
              })}
            </div>
          ))
        )}
      </div>
    </div>
  )
}

// Small clock trigger button to put in module headers
export function HistoryTrigger({ moduleId, onOpen }) {
  return (
    <button
      onClick={onOpen}
      title="Version history"
      style={{
        background: 'none',
        border: 'none',
        color: 'var(--text-dim)',
        cursor: 'pointer',
        padding: 4,
        borderRadius: 4,
        display: 'flex',
        alignItems: 'center',
      }}
      onMouseEnter={e => e.currentTarget.style.color = 'var(--text)'}
      onMouseLeave={e => e.currentTarget.style.color = 'var(--text-dim)'}
    >
      <Clock size={15} />
    </button>
  )
}
